apiVersion: v1
kind: Service
metadata:
  name: statelessback
spec:
  type: ClusterIP
  selector:
    app: statelessback
  ports:
    - name: statelessback
      protocol: TCP
      port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: statelessfront
spec:
  type: ClusterIP
  selector:
    app: statelessfront
  ports:
    - name: statelessfront
      protocol: TCP
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - name: zipkin
      protocol: TCP
      port: 9411
