sources:
    - type: "environment-variables"
    - type: "system-properties"
    - type: "file"
      properties:
          path: "conf/config.properties"
          optional: true
          change-watcher:
            type: "file"
            properties:
              initial-delay-millis: 10000
              delay-millis: 5000
    - type: "classpath"
      properties:
          resource: "META-INF/microprofile-config.properties"